### ISSUE TITLE
about xuidreserve

### ISSUE THREAD

**Issue by ProjectSky** [shqke/imatchext#1]
is possible to get xuidReserve from servers?

> mm_debugprint
```
CMatchSessionOnlineHost [ state=7 ]
System data:
  SysSessionData {
    type host
    xuidReserve u64( 109775240923396424 = 0x1860000005F3948 )
    xuidHost u64( 76561198034557379 = 0x1100001046D99C3 )
    state game
  }
```

**Comment by shqke** [comment]
Added method [GetReservationCookie](https://github.com/shqke/imatchext/blob/master/extra/scripting/include/imatchext.inc#L16-L22).

**Comment by ProjectSky** [comment]
> Added method [GetReservationCookie](https://github.com/shqke/imatchext/blob/master/extra/scripting/include/imatchext.inc#L16-L22).

nice, but use GetReservationCookie i get ```Not reserved```

``` cpp
public void OnPluginStart()
{
	RegConsoleCmd("sm_test", Command_Test);
}

public Action Command_Test(int client, int args)
{
        int cookie[2];
        if (GetReservationCookie(cookie)) {
            if (cookie[1] != 0) {
                PrintToServer("Reserved: 0x%08X%08X", cookie[1], cookie[0]);
            }
            else {
                PrintToServer("Not reserved");
            }
        }
}
```

* client console (mm_debugprint)

```
CMatchSessionOnlineHost [ state=7 ]
System data:
  SysSessionData {
    type host
    xuidReserve u64( 109775240925783637 = 0x18600000083A655 )
    xuidHost u64( 76561198034557379 = 0x1100001046D99C3 )
    state game
  }
```

l4dtoolz? it set server is unreserved, if the server is unreserved, can get xuidReserve?(client always get it)

**Comment by shqke** [comment]
`mm_debugprint` on a client prints a lobby ID (= xuidReserve, reservation cookie), he (a client) is currently a member/owner of.
Server only stores a lobby ID to broadcast to newly connected clients.

So no, if your l4dtoolz does unreserve - cookie will be unset on a server, but current clients will not leave a lobby they're members of.

**Comment by ProjectSky** [comment]
> `mm_debugprint` on a client prints a lobby ID (= xuidReserve, reservation cookie), he (a client) is currently a member/owner of.
> Server only stores a lobby ID to broadcast to newly connected clients.
> 
> So no, if your l4dtoolz does unreserve - cookie will be unset on a server, but current clients will not leave a lobby they're members of.

thx answers, this extension helped me a lot.
