### ISSUE TITLE
Unable to load extension "langparser.ext"

### ISSUE THREAD

**Issue by umlka** [shqke/imatchext#4]
L 04/20/2022 - 00:50:56: [SM] Unable to load extension "langparser.ext": /home/l4d2/l4d2/left4dead2/addons/sourcemod/extensions/langparser.ext.so: cannot open shared object file: No such file or directory

**Comment by shqke** [comment]
Hi!

I've added a missing link to extension into `README.md`, but doesn't seem like I can do much about supressing a warning message.

**Comment by shqke** [comment]
Looking at [sourcemod source code](https://github.com/alliedmodders/sourcemod/blob/636161e18321715f2cff74917740e98854e0c143/core/logic/ExtensionSys.cpp#L894-L897), it feels like a 
```cpp
	/* This function doesn't really need to do anything now.  We make sure the 
	 * other extension is loaded, but handling of dependencies is really done 
	 * by the interface fetcher.
	 */
	if (required || autoload)
	{
		LoadAutoExtension(file);
	}
```
should be
```cpp
	/* This function doesn't really need to do anything now.  We make sure the 
	 * other extension is loaded, but handling of dependencies is really done 
	 * by the interface fetcher.
	 */
	if (required || autoload)
	{
		LoadAutoExtension(file, required);
	}
```

**Comment by umlka** [comment]
After installing the langparser.ext extension, the error is gone

**Comment by shqke** [comment]
> the error is gone

Extension would work anyway, I can see that having error message being logged is still annoying though. 👍
