### ISSUE TITLE
GLIBC_2.33 not found

### ISSUE THREAD

**Issue by Quesoteric** [shqke/imatchext#5]
<FAILED> file "imatchext.ext.2.l4d2.so":
/lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.33' not found 
(required by /Left4Dead2DedicatedServer/left4dead2/addons/sourcemod/extensions/imatchext.ext)

**Comment by Quesoteric** [comment]
Issue on 18.04 Ubuntu

**Comment by Quesoteric** [comment]
Metamod:Source version 1.11.0-dev+1153
SourceMod Version: 1.11.0.6945
Tested with "imatchext-smlatest-linux-0b271df"

**Comment by Quesoteric** [comment]
tried to get current glibc version
results
(Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27

**Comment by shqke** [comment]
Try [oldlinux build](https://github.com/shqke/imatchext/actions/runs/6734551522).

**Comment by Quesoteric** [comment]
Works just fine, thank you
