### ISSUE TITLE
Question regatding error "bin/libstdc++.so.6: version `GLIBCXX_3.4.21' not found"

### ISSUE THREAD

**Issue by jensewe** [shqke/imatchext#6]
Error when loading the extension ([smlatest-oldlinux](https://github.com/shqke/imatchext/actions/runs/9259633922)).

OS: Ubuntu 20.04
SourceMod: 1.12.0.7137
Metamod: 1.12 - build 1194

I doubt if this is an issue for anyone else, but the binary seems to be included in the server content, in which case the extension could just be not usable on any linux machine.

**Comment by shqke** [comment]
Didn't notice, it should be working now.
